### PR TITLE
jitpack.io integration

### PR DESCRIPTION
**Pull request by mironbalcerzak**
Hey hey 

This PR contains 2 changes:
1. i moved PNGs to "/docs" dir
2. added gradle task to auto-generate pom.xml each time gradle install is invoked - apparently, jitpack.io is not handling gradle projects so I could not use jmxbuilder as github dependency (through jitpack repository)

BTW. Great stuff on the project. That's exactly what I needed =)

Have a great day wherever you are 👍
-mb

### CODE REVIEW

**Comment by wsargent** [comment]
What is jitpack integration?

**Comment by mironbalcerzak** [comment]
https://jitpack.io/

if set as a repository in maven/gradle, one can use github.com project as a direct dependency in the project, without the need to release it maven artifact repo (ie. com.github.tersesystems:jmxbuilder:[gitcommit-hash])

for some reason, jitpack was not discovering the gradle project - have no problems if pom.xml is present though..

**Comment by wsargent** [comment]
I had to take this out to get it through the upgraded Gradle, but I will put it back in a patch release.

**Comment by mironbalcerzak** [comment]
@wsargent - no problem at all :) thanks for the effort 👍

**Comment by mironbalcerzak** [comment]
ive introduced it as there were some changes in github that we not released

**Comment by wsargent** [comment]
should be working now https://jitpack.io/#tersesystems/jmxbuilder/main-SNAPSHOT

**Pull request merged**
