### PR TITLE
Jdk9+ support

### PR DESCRIPTION
**Pull request by mironbalcerzak**
Hey there again,
Here's JDK9+ support - i took a good look around the Java JMX API and i haven't found a decent way of creating OpenType object.  What I found though is a slightly cleaner way of creating OpenType -  and that's what I introduced (well - copied single class from java internals and slightly patched (removed unnecessary bits and pieces)) so now there are no complaints re java modules in jdk9+

Have a great day =)
-mb

### CODE REVIEW

**Comment by wsargent** [comment]
Thanks, I will take a look!

**Comment by wsargent** [comment]
Does it not compile in JDK 9+ otherwise, or is it just a warning?

**Comment by mironbalcerzak** [comment]
project, as it was, was compilng in jdk17 (that's what i tested against).
However failed to start because jmxbuilder was using internal java classes, that are no longer exposed

**Comment by mironbalcerzak** [comment]
@wsargent bump :)

**Comment by wsargent** [comment]
@mironbalcerzak thanks for the bump!  looking now.

**Comment by wsargent** [comment]
1.0.0 is released!  (jetpack is not working yet)

**Pull request merged**
